
const SERVER_URL_PREFIX = 'https://soasga.com/api/v1';

const AUTHORIZATION = 'AUTO-CORRECTION-AUTHORIZATION';
const ACCESS_TOKEN = 'AUTO-CORRECTION-ACCESS-TOKEN';
const ADMIN_DATA = 'AUTO-CORRECTION-ADMIN-DATA';



